import { subDays, format } from "date-fns";

export const generateTrendData = (days = 30) => {
  return Array.from({ length: days }).map((_, i) => {
    const date = subDays(new Date(), days - 1 - i);
    return {
      date: format(date, "MMM dd"),
      facebook: Math.floor(Math.random() * 5000) + 2000,
      youtube: Math.floor(Math.random() * 8000) + 4000,
      tiktok: Math.floor(Math.random() * 12000) + 6000,
      total: 0 // Will be calculated below
    };
  }).map(d => ({ ...d, total: d.facebook + d.youtube + d.tiktok }));
};

export const MOCK_KPIS = [
  {
    title: "Tổng Reach (Tiếp Cận)",
    value: "18.4M",
    change: "+14.2%",
    trend: "up",
    period: "vs tháng trước",
    platforms: ["youtube", "tiktok", "facebook"],
    trendData: [4, 5, 4, 6, 7, 6, 8, 9, 8, 10, 12, 14],
  },
  {
    title: "Tổng Tương Tác",
    value: "2.1M",
    change: "+8.5%",
    trend: "up",
    period: "vs tháng trước",
    platforms: ["youtube", "tiktok", "facebook"],
    trendData: [3, 4, 3, 5, 4, 6, 7, 8, 7, 8, 9, 10],
  },
  {
    title: "Tỷ Lệ Tăng Trưởng",
    value: "12.4%",
    change: "+2.1%",
    trend: "up",
    period: "vs tháng trước",
    platforms: ["youtube", "tiktok"],
    trendData: [2, 2, 3, 2, 4, 3, 5, 4, 6, 5, 7, 8],
  },
  {
    title: "Lượt Xem Video",
    value: "34.2M",
    change: "-1.2%",
    trend: "down",
    period: "vs tháng trước",
    platforms: ["youtube", "tiktok", "facebook"],
    trendData: [14, 13, 15, 12, 10, 11, 9, 8, 7, 8, 6, 5],
  },
  {
    title: "Followers Mới",
    value: "84.5K",
    change: "+24.1%",
    trend: "up",
    period: "vs tháng trước",
    platforms: ["tiktok", "youtube"],
    trendData: [1, 2, 1, 3, 4, 5, 4, 6, 8, 9, 12, 15],
  },
  {
    title: "Tần Suất Đăng Bài",
    value: "94%",
    change: "-2.0%",
    trend: "down",
    period: "vs kế hoạch",
    platforms: ["facebook", "tiktok", "youtube"],
    trendData: [10, 10, 9, 10, 10, 8, 9, 10, 10, 9, 8, 8],
  },
];

export const PLATFORM_MIX_DATA = [
  { name: 'TikTok', value: 45, fill: '#0ea5e9' },
  { name: 'YouTube', value: 35, fill: '#ef4444' },
  { name: 'Facebook', value: 20, fill: '#3b82f6' },
];

export const MOCK_GROUP_CHANNELS = [
  {
    "id": "fb1",
    "groupId": "g1",
    "name": "Facebook Channel 1",
    "platform": "facebook",
    "followers": "0.7M",
    "handle": "@fb_channel_1",
    "status": "connected",
    "lastSync": "10 phút trước",
    "avatar": "https://api.dicebear.com/7.x/identicon/svg?seed=avatar1"
  },
  {
    "id": "fb2",
    "groupId": "g2",
    "name": "Facebook Channel 2",
    "platform": "facebook",
    "followers": "3.6M",
    "handle": "@fb_channel_2",
    "status": "connected",
    "lastSync": "10 phút trước",
    "avatar": "https://api.dicebear.com/7.x/identicon/svg?seed=avatar2"
  },
  {
    "id": "fb3",
    "groupId": "g3",
    "name": "Facebook Channel 3",
    "platform": "facebook",
    "followers": "1.4M",
    "handle": "@fb_channel_3",
    "status": "connected",
    "lastSync": "10 phút trước",
    "avatar": "https://api.dicebear.com/7.x/identicon/svg?seed=avatar3"
  },
  {
    "id": "fb4",
    "groupId": "g4",
    "name": "Facebook Channel 4",
    "platform": "facebook",
    "followers": "3.2M",
    "handle": "@fb_channel_4",
    "status": "connected",
    "lastSync": "10 phút trước",
    "avatar": "https://api.dicebear.com/7.x/identicon/svg?seed=avatar4"
  },
  {
    "id": "fb5",
    "groupId": "g1",
    "name": "Facebook Channel 5",
    "platform": "facebook",
    "followers": "1.8M",
    "handle": "@fb_channel_5",
    "status": "connected",
    "lastSync": "10 phút trước",
    "avatar": "https://api.dicebear.com/7.x/identicon/svg?seed=avatar5"
  },
  {
    "id": "fb6",
    "groupId": "g2",
    "name": "Facebook Channel 6",
    "platform": "facebook",
    "followers": "3.6M",
    "handle": "@fb_channel_6",
    "status": "connected",
    "lastSync": "10 phút trước",
    "avatar": "https://api.dicebear.com/7.x/identicon/svg?seed=avatar6"
  },
  {
    "id": "fb7",
    "groupId": "g3",
    "name": "Facebook Channel 7",
    "platform": "facebook",
    "followers": "3.3M",
    "handle": "@fb_channel_7",
    "status": "connected",
    "lastSync": "10 phút trước",
    "avatar": "https://api.dicebear.com/7.x/identicon/svg?seed=avatar7"
  },
  {
    "id": "fb8",
    "groupId": "g4",
    "name": "Facebook Channel 8",
    "platform": "facebook",
    "followers": "0.7M",
    "handle": "@fb_channel_8",
    "status": "connected",
    "lastSync": "10 phút trước",
    "avatar": "https://api.dicebear.com/7.x/identicon/svg?seed=avatar8"
  },
  {
    "id": "fb9",
    "groupId": "g1",
    "name": "Facebook Channel 9",
    "platform": "facebook",
    "followers": "3.3M",
    "handle": "@fb_channel_9",
    "status": "connected",
    "lastSync": "10 phút trước",
    "avatar": "https://api.dicebear.com/7.x/identicon/svg?seed=avatar9"
  },
  {
    "id": "fb10",
    "groupId": "g2",
    "name": "Facebook Channel 10",
    "platform": "facebook",
    "followers": "3.2M",
    "handle": "@fb_channel_10",
    "status": "connected",
    "lastSync": "10 phút trước",
    "avatar": "https://api.dicebear.com/7.x/identicon/svg?seed=avatar10"
  },
  {
    "id": "yt1",
    "groupId": "g1",
    "name": "YouTube Channel 1",
    "platform": "youtube",
    "followers": "4.6M",
    "handle": "@yt_channel_1",
    "status": "connected",
    "lastSync": "10 phút trước",
    "avatar": "https://api.dicebear.com/7.x/identicon/svg?seed=avatar11"
  },
  {
    "id": "yt2",
    "groupId": "g2",
    "name": "YouTube Channel 2",
    "platform": "youtube",
    "followers": "1.3M",
    "handle": "@yt_channel_2",
    "status": "connected",
    "lastSync": "10 phút trước",
    "avatar": "https://api.dicebear.com/7.x/identicon/svg?seed=avatar12"
  },
  {
    "id": "yt3",
    "groupId": "g3",
    "name": "YouTube Channel 3",
    "platform": "youtube",
    "followers": "0.6M",
    "handle": "@yt_channel_3",
    "status": "connected",
    "lastSync": "10 phút trước",
    "avatar": "https://api.dicebear.com/7.x/identicon/svg?seed=avatar13"
  },
  {
    "id": "yt4",
    "groupId": "g4",
    "name": "YouTube Channel 4",
    "platform": "youtube",
    "followers": "1.0M",
    "handle": "@yt_channel_4",
    "status": "connected",
    "lastSync": "10 phút trước",
    "avatar": "https://api.dicebear.com/7.x/identicon/svg?seed=avatar14"
  },
  {
    "id": "yt5",
    "groupId": "g1",
    "name": "YouTube Channel 5",
    "platform": "youtube",
    "followers": "1.5M",
    "handle": "@yt_channel_5",
    "status": "connected",
    "lastSync": "10 phút trước",
    "avatar": "https://api.dicebear.com/7.x/identicon/svg?seed=avatar15"
  },
  {
    "id": "tt1",
    "groupId": "g1",
    "name": "TikTok Channel 1",
    "platform": "tiktok",
    "followers": "3.6M",
    "handle": "@tt_channel_1",
    "status": "connected",
    "lastSync": "10 phút trước",
    "avatar": "https://api.dicebear.com/7.x/identicon/svg?seed=avatar16"
  },
  {
    "id": "tt2",
    "groupId": "g2",
    "name": "TikTok Channel 2",
    "platform": "tiktok",
    "followers": "4.5M",
    "handle": "@tt_channel_2",
    "status": "connected",
    "lastSync": "10 phút trước",
    "avatar": "https://api.dicebear.com/7.x/identicon/svg?seed=avatar17"
  },
  {
    "id": "tt3",
    "groupId": "g3",
    "name": "TikTok Channel 3",
    "platform": "tiktok",
    "followers": "3.1M",
    "handle": "@tt_channel_3",
    "status": "connected",
    "lastSync": "10 phút trước",
    "avatar": "https://api.dicebear.com/7.x/identicon/svg?seed=avatar18"
  },
  {
    "id": "tt4",
    "groupId": "g4",
    "name": "TikTok Channel 4",
    "platform": "tiktok",
    "followers": "3.3M",
    "handle": "@tt_channel_4",
    "status": "connected",
    "lastSync": "10 phút trước",
    "avatar": "https://api.dicebear.com/7.x/identicon/svg?seed=avatar19"
  },
  {
    "id": "tt5",
    "groupId": "g1",
    "name": "TikTok Channel 5",
    "platform": "tiktok",
    "followers": "3.6M",
    "handle": "@tt_channel_5",
    "status": "connected",
    "lastSync": "10 phút trước",
    "avatar": "https://api.dicebear.com/7.x/identicon/svg?seed=avatar20"
  }
];

export const PILLAR_DATA = [
  { subject: 'Sản Phẩm', value: 120, fullMark: 150 },
  { subject: 'Giáo Dục', value: 98, fullMark: 150 },
  { subject: 'Hậu Trường', value: 86, fullMark: 150 },
  { subject: 'Khách Hàng', value: 50, fullMark: 150 },
  { subject: 'Bắt Trend', value: 110, fullMark: 150 },
];

export const UPCOMING_POSTS = [
  { id: 1, title: 'Demo Arc Reactor V2', time: '14:00 Hôm nay', platform: 'youtube', status: 'ready' },
  { id: 2, title: 'Bí kíp tiết kiệm pin', time: '18:00 Hôm nay', platform: 'tiktok', status: 'approval' },
  { id: 3, title: 'Tặng quà tri ân KH', time: '09:00 Ngày mai', platform: 'facebook', status: 'draft' },
];

export const MOCK_CALENDAR_EVENTS = [
  { id: "e1", title: "Ra mắt sản phẩm: Định hình tương lai", platform: "youtube", type: "video", status: "published", time: "10:00", dateOffset: -2, perfScore: 98 },
  { id: "e2", title: "Trend biến hình 10s cực gắt", platform: "tiktok", type: "short", status: "published", time: "14:30", dateOffset: -1, perfScore: 99 },
  { id: "e3", title: "Phỏng vấn độc quyền cùng CEO", platform: "facebook", type: "video", status: "published", time: "09:00", dateOffset: -5, perfScore: 72 },
  { id: "e4", title: "Review setup góc làm việc 2026", platform: "youtube", type: "video", status: "published", time: "19:00", dateOffset: -7, perfScore: 88 },
  { id: "e5", title: "Livestream Q&A Mùa Hè", platform: "youtube", type: "live", status: "scheduled", time: "20:00", dateOffset: 2, perfScore: null },
  { id: "e6", title: "Bí kíp chống cháy túi (Short)", platform: "tiktok", type: "short", status: "approval", time: "11:00", dateOffset: 1, perfScore: null },
  { id: "e7", title: "Cảnh báo bảo mật hệ thống", platform: "facebook", type: "image", status: "error", time: "15:00", dateOffset: 0, perfScore: null },
  { id: "e8", title: "Teaser: Kỷ nguyên mới", platform: "youtube", type: "video", status: "draft", time: "18:00", dateOffset: 3, perfScore: null },
  { id: "e9", title: "Hậu trường phỏng vấn CEO", platform: "tiktok", type: "short", status: "scheduled", time: "21:00", dateOffset: 0, perfScore: null },
  { id: "e10", title: "Thực tế ảo AR/VR 2026", platform: "youtube", type: "video", status: "scheduled", time: "09:00", dateOffset: 5, perfScore: null },
  { id: "e11", title: "Khảo sát ý kiến người dùng", platform: "facebook", type: "image", status: "draft", time: "14:00", dateOffset: -3, perfScore: 45 },
  { id: "e12", title: "Công bố người trúng thưởng", platform: "facebook", type: "video", status: "scheduled", time: "16:00", dateOffset: 4, perfScore: null },
];

export const MOCK_TOP_CONTENT = [
  { id: "1", title: "Ra mắt sản phẩm: Định hình tương lai", platform: "youtube", type: "video", reach: 2400000, engagement: "245K", engagementRate: 10.2, comments: 12400, shares: 8500, saves: 4200, followersGained: 15400, score: 98, pillar: "Sản Phẩm", tags: ["Launch", "Tech"], growthImpact: "+High", publishedAt: subDays(new Date(), 2).toISOString(), thumbnail: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=500&q=80" },
  { id: "2", title: "Trend biến hình 10s cực gắt", platform: "tiktok", type: "short", reach: 5200000, engagement: "890K", engagementRate: 17.1, comments: 45000, shares: 120000, saves: 88000, followersGained: 65000, score: 99, pillar: "Bắt Trend", tags: ["Viral", "Transition"], growthImpact: "+Viral", publishedAt: subDays(new Date(), 1).toISOString(), thumbnail: "https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=500&q=80" },
  { id: "3", title: "Phỏng vấn độc quyền cùng CEO", platform: "facebook", type: "video", reach: 850000, engagement: "42K", engagementRate: 4.9, comments: 1200, shares: 800, saves: 150, followersGained: 450, score: 72, pillar: "Hậu Trường", tags: ["Interview", "Leadership"], growthImpact: "Medium", publishedAt: subDays(new Date(), 5).toISOString(), thumbnail: "https://images.unsplash.com/photo-1551818255-e6e10975bc17?w=500&q=80" },
  { id: "4", title: "Review setup góc làm việc 2026", platform: "youtube", type: "video", reach: 1200000, engagement: "95K", engagementRate: 7.9, comments: 3400, shares: 1200, saves: 8900, followersGained: 4200, score: 88, pillar: "Cộng Đồng", tags: ["Setup", "Workspace", "Review"], growthImpact: "+High", publishedAt: subDays(new Date(), 7).toISOString(), thumbnail: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=500&q=80" },
  { id: "5", title: "Mẹo tối ưu năng suất (Short)", platform: "tiktok", type: "short", reach: 890000, engagement: "112K", engagementRate: 12.5, comments: 890, shares: 15600, saves: 24000, followersGained: 5600, score: 85, pillar: "Giáo Dục", tags: ["Tips", "Productivity"], growthImpact: "Medium", publishedAt: subDays(new Date(), 3).toISOString(), thumbnail: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=500&q=80" },
  { id: "6", title: "Livestream Q&A tháng 4", platform: "youtube", type: "live", reach: 450000, engagement: "85K", engagementRate: 18.8, comments: 15000, shares: 400, saves: 50, followersGained: 1200, score: 82, pillar: "Khách Hàng", tags: ["Q&A", "Live"], growthImpact: "Medium", publishedAt: subDays(new Date(), 10).toISOString(), thumbnail: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=500&q=80" },
  { id: "7", title: "Album ảnh: Ngày hội công nghệ", platform: "facebook", type: "image", reach: 320000, engagement: "15K", engagementRate: 4.6, comments: 450, shares: 210, saves: 0, followersGained: 120, score: 65, pillar: "Sự Kiện", tags: ["Event", "Photos"], growthImpact: "Low", publishedAt: subDays(new Date(), 4).toISOString(), thumbnail: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=500&q=80" },
  { id: "8", title: "Hack não: 3 tip dùng Excel pro", platform: "tiktok", type: "short", reach: 3100000, engagement: "430K", engagementRate: 13.8, comments: 4500, shares: 85000, saves: 120000, followersGained: 24000, score: 94, pillar: "Giáo Dục", tags: ["Excel", "Tutorial", "Tips"], growthImpact: "+High", publishedAt: subDays(new Date(), 6).toISOString(), thumbnail: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=500&q=80" },
  { id: "9", title: "Podcast Ep. 45: Tech Trends", platform: "youtube", type: "video", reach: 670000, engagement: "54K", engagementRate: 8.0, comments: 1200, shares: 900, saves: 3400, followersGained: 850, score: 76, pillar: "Giáo Dục", tags: ["Podcast", "Trends"], growthImpact: "Medium", publishedAt: subDays(new Date(), 12).toISOString(), thumbnail: "https://images.unsplash.com/photo-1589903308904-1010c2294adc?w=500&q=80" },
  { id: "10", title: "Giveaway 2M Subscribers", platform: "facebook", type: "image", reach: 1800000, engagement: "320K", engagementRate: 17.7, comments: 185000, shares: 45000, saves: 1200, followersGained: 34000, score: 96, pillar: "Khách Hàng", tags: ["Giveaway", "Milestone"], growthImpact: "+Viral", publishedAt: subDays(new Date(), 1).toISOString(), thumbnail: "https://images.unsplash.com/photo-1513201099705-a9746e1e201f?w=500&q=80" },
];

export const MOCK_ALERTS = [
  { id: "a1", title: "Tăng trưởng bất thường", description: "TikTok engagement tăng vọt đột biến (340%) ở video '#Trend'.", severity: "success", time: "1 giờ trước", ctaText: "Boost Post", variant: "default" },
  { id: "a2", title: "Reach giảm mạnh", description: "Youtube Reach hụt 15% so với target tuần hiện tại.", severity: "danger", time: "4 giờ trước", ctaText: "Phân tích nguyên nhân", variant: "default" },
  { id: "a3", title: "Lỗi kết nối Facebook", description: "Mất kết nối API với Stark Resilient Page. Cần re-auth.", severity: "warning", time: "5 giờ trước", ctaText: "Kết nối lại", variant: "default" },
  { id: "a4", title: "Thiếu lịch đăng bài", description: "Trống lịch đăng cho kênh TikTok vào Thứ Sáu tới.", severity: "info", time: "12 giờ trước", ctaText: "Lên lịch ngay", variant: "list" },
];

export const CONTENT_TABLE_DATA = [
  {
    "id": "cc_1",
    "thumbnail": "https://picsum.photos/seed/thumb21/200/200",
    "title": "Content for Facebook Channel 1 - Post 1",
    "channel": "Facebook Channel 1",
    "platform": "facebook",
    "date": "2026-04-19T10:00:00Z",
    "reach": 1282981,
    "engagement": 238251,
    "comments": 2511,
    "shares": 1711,
    "saves": 1554,
    "followersGained": 252,
    "performanceScore": 90,
    "status": "published"
  },
  {
    "id": "cc_2",
    "thumbnail": "https://picsum.photos/seed/thumb22/200/200",
    "title": "Content for Facebook Channel 2 - Post 1",
    "channel": "Facebook Channel 2",
    "platform": "facebook",
    "date": "2026-04-15T10:00:00Z",
    "reach": 756140,
    "engagement": 453445,
    "comments": 4277,
    "shares": 4842,
    "saves": 850,
    "followersGained": 222,
    "performanceScore": 66,
    "status": "published"
  },
  {
    "id": "cc_3",
    "thumbnail": "https://picsum.photos/seed/thumb23/200/200",
    "title": "Content for Facebook Channel 3 - Post 1",
    "channel": "Facebook Channel 3",
    "platform": "facebook",
    "date": "2026-04-13T10:00:00Z",
    "reach": 15161,
    "engagement": 94149,
    "comments": 5355,
    "shares": 907,
    "saves": 1214,
    "followersGained": 326,
    "performanceScore": 92,
    "status": "published"
  },
  {
    "id": "cc_4",
    "thumbnail": "https://picsum.photos/seed/thumb24/200/200",
    "title": "Content for Facebook Channel 3 - Post 2",
    "channel": "Facebook Channel 3",
    "platform": "facebook",
    "date": "2026-04-13T10:00:00Z",
    "reach": 1139215,
    "engagement": 491590,
    "comments": 1592,
    "shares": 166,
    "saves": 236,
    "followersGained": 332,
    "performanceScore": 80,
    "status": "draft"
  },
  {
    "id": "cc_5",
    "thumbnail": "https://picsum.photos/seed/thumb25/200/200",
    "title": "Content for Facebook Channel 4 - Post 1",
    "channel": "Facebook Channel 4",
    "platform": "facebook",
    "date": "2026-04-01T10:00:00Z",
    "reach": 839081,
    "engagement": 26093,
    "comments": 4006,
    "shares": 377,
    "saves": 1467,
    "followersGained": 302,
    "performanceScore": 93,
    "status": "published"
  },
  {
    "id": "cc_6",
    "thumbnail": "https://picsum.photos/seed/thumb26/200/200",
    "title": "Content for Facebook Channel 4 - Post 2",
    "channel": "Facebook Channel 4",
    "platform": "facebook",
    "date": "2026-04-19T10:00:00Z",
    "reach": 823626,
    "engagement": 420698,
    "comments": 7392,
    "shares": 826,
    "saves": 1274,
    "followersGained": 443,
    "performanceScore": 62,
    "status": "published"
  },
  {
    "id": "cc_7",
    "thumbnail": "https://picsum.photos/seed/thumb27/200/200",
    "title": "Content for Facebook Channel 4 - Post 3",
    "channel": "Facebook Channel 4",
    "platform": "facebook",
    "date": "2026-04-16T10:00:00Z",
    "reach": 942790,
    "engagement": 144699,
    "comments": 2637,
    "shares": 71,
    "saves": 1552,
    "followersGained": 391,
    "performanceScore": 72,
    "status": "draft"
  },
  {
    "id": "cc_8",
    "thumbnail": "https://picsum.photos/seed/thumb28/200/200",
    "title": "Content for Facebook Channel 5 - Post 1",
    "channel": "Facebook Channel 5",
    "platform": "facebook",
    "date": "2026-04-02T10:00:00Z",
    "reach": 521271,
    "engagement": 95831,
    "comments": 8155,
    "shares": 4993,
    "saves": 936,
    "followersGained": 300,
    "performanceScore": 89,
    "status": "published"
  },
  {
    "id": "cc_9",
    "thumbnail": "https://picsum.photos/seed/thumb29/200/200",
    "title": "Content for Facebook Channel 5 - Post 2",
    "channel": "Facebook Channel 5",
    "platform": "facebook",
    "date": "2026-04-12T10:00:00Z",
    "reach": 1636438,
    "engagement": 351817,
    "comments": 1141,
    "shares": 1616,
    "saves": 635,
    "followersGained": 304,
    "performanceScore": 75,
    "status": "published"
  },
  {
    "id": "cc_10",
    "thumbnail": "https://picsum.photos/seed/thumb30/200/200",
    "title": "Content for Facebook Channel 6 - Post 1",
    "channel": "Facebook Channel 6",
    "platform": "facebook",
    "date": "2026-04-01T10:00:00Z",
    "reach": 1352239,
    "engagement": 139703,
    "comments": 7334,
    "shares": 96,
    "saves": 1684,
    "followersGained": 55,
    "performanceScore": 73,
    "status": "published"
  },
  {
    "id": "cc_11",
    "thumbnail": "https://picsum.photos/seed/thumb31/200/200",
    "title": "Content for Facebook Channel 6 - Post 2",
    "channel": "Facebook Channel 6",
    "platform": "facebook",
    "date": "2026-04-09T10:00:00Z",
    "reach": 1298273,
    "engagement": 344997,
    "comments": 1110,
    "shares": 2407,
    "saves": 579,
    "followersGained": 285,
    "performanceScore": 74,
    "status": "published"
  },
  {
    "id": "cc_12",
    "thumbnail": "https://picsum.photos/seed/thumb32/200/200",
    "title": "Content for Facebook Channel 6 - Post 3",
    "channel": "Facebook Channel 6",
    "platform": "facebook",
    "date": "2026-04-05T10:00:00Z",
    "reach": 528122,
    "engagement": 56704,
    "comments": 8141,
    "shares": 4418,
    "saves": 1582,
    "followersGained": 75,
    "performanceScore": 90,
    "status": "published"
  },
  {
    "id": "cc_13",
    "thumbnail": "https://picsum.photos/seed/thumb33/200/200",
    "title": "Content for Facebook Channel 7 - Post 1",
    "channel": "Facebook Channel 7",
    "platform": "facebook",
    "date": "2026-04-12T10:00:00Z",
    "reach": 734960,
    "engagement": 424563,
    "comments": 5270,
    "shares": 1807,
    "saves": 1391,
    "followersGained": 118,
    "performanceScore": 67,
    "status": "published"
  },
  {
    "id": "cc_14",
    "thumbnail": "https://picsum.photos/seed/thumb34/200/200",
    "title": "Content for Facebook Channel 8 - Post 1",
    "channel": "Facebook Channel 8",
    "platform": "facebook",
    "date": "2026-04-02T10:00:00Z",
    "reach": 1532790,
    "engagement": 273003,
    "comments": 8398,
    "shares": 3463,
    "saves": 1764,
    "followersGained": 145,
    "performanceScore": 90,
    "status": "published"
  },
  {
    "id": "cc_15",
    "thumbnail": "https://picsum.photos/seed/thumb35/200/200",
    "title": "Content for Facebook Channel 9 - Post 1",
    "channel": "Facebook Channel 9",
    "platform": "facebook",
    "date": "2026-04-03T10:00:00Z",
    "reach": 11697,
    "engagement": 440751,
    "comments": 7640,
    "shares": 4628,
    "saves": 520,
    "followersGained": 75,
    "performanceScore": 89,
    "status": "published"
  },
  {
    "id": "cc_16",
    "thumbnail": "https://picsum.photos/seed/thumb36/200/200",
    "title": "Content for Facebook Channel 9 - Post 2",
    "channel": "Facebook Channel 9",
    "platform": "facebook",
    "date": "2026-04-12T10:00:00Z",
    "reach": 1401069,
    "engagement": 356593,
    "comments": 1146,
    "shares": 1319,
    "saves": 1576,
    "followersGained": 215,
    "performanceScore": 98,
    "status": "published"
  },
  {
    "id": "cc_17",
    "thumbnail": "https://picsum.photos/seed/thumb37/200/200",
    "title": "Content for Facebook Channel 10 - Post 1",
    "channel": "Facebook Channel 10",
    "platform": "facebook",
    "date": "2026-04-13T10:00:00Z",
    "reach": 1818443,
    "engagement": 404935,
    "comments": 5213,
    "shares": 4940,
    "saves": 91,
    "followersGained": 415,
    "performanceScore": 64,
    "status": "published"
  },
  {
    "id": "cc_18",
    "thumbnail": "https://picsum.photos/seed/thumb38/200/200",
    "title": "Content for Facebook Channel 10 - Post 2",
    "channel": "Facebook Channel 10",
    "platform": "facebook",
    "date": "2026-04-13T10:00:00Z",
    "reach": 1219137,
    "engagement": 402464,
    "comments": 7507,
    "shares": 580,
    "saves": 1035,
    "followersGained": 255,
    "performanceScore": 67,
    "status": "draft"
  },
  {
    "id": "cc_19",
    "thumbnail": "https://picsum.photos/seed/thumb39/200/200",
    "title": "Content for YouTube Channel 1 - Post 1",
    "channel": "YouTube Channel 1",
    "platform": "youtube",
    "date": "2026-04-19T10:00:00Z",
    "reach": 1121600,
    "engagement": 67836,
    "comments": 1974,
    "shares": 2102,
    "saves": 268,
    "followersGained": 430,
    "performanceScore": 96,
    "status": "published"
  },
  {
    "id": "cc_20",
    "thumbnail": "https://picsum.photos/seed/thumb40/200/200",
    "title": "Content for YouTube Channel 1 - Post 2",
    "channel": "YouTube Channel 1",
    "platform": "youtube",
    "date": "2026-04-01T10:00:00Z",
    "reach": 1008061,
    "engagement": 208793,
    "comments": 5071,
    "shares": 3495,
    "saves": 778,
    "followersGained": 388,
    "performanceScore": 66,
    "status": "published"
  },
  {
    "id": "cc_21",
    "thumbnail": "https://picsum.photos/seed/thumb41/200/200",
    "title": "Content for YouTube Channel 1 - Post 3",
    "channel": "YouTube Channel 1",
    "platform": "youtube",
    "date": "2026-04-18T10:00:00Z",
    "reach": 316406,
    "engagement": 480506,
    "comments": 9339,
    "shares": 10,
    "saves": 1002,
    "followersGained": 325,
    "performanceScore": 90,
    "status": "published"
  },
  {
    "id": "cc_22",
    "thumbnail": "https://picsum.photos/seed/thumb42/200/200",
    "title": "Content for YouTube Channel 2 - Post 1",
    "channel": "YouTube Channel 2",
    "platform": "youtube",
    "date": "2026-04-16T10:00:00Z",
    "reach": 1197297,
    "engagement": 129903,
    "comments": 9956,
    "shares": 3890,
    "saves": 1064,
    "followersGained": 225,
    "performanceScore": 91,
    "status": "draft"
  },
  {
    "id": "cc_23",
    "thumbnail": "https://picsum.photos/seed/thumb43/200/200",
    "title": "Content for YouTube Channel 2 - Post 2",
    "channel": "YouTube Channel 2",
    "platform": "youtube",
    "date": "2026-04-07T10:00:00Z",
    "reach": 684909,
    "engagement": 5299,
    "comments": 8050,
    "shares": 2551,
    "saves": 1460,
    "followersGained": 242,
    "performanceScore": 64,
    "status": "draft"
  },
  {
    "id": "cc_24",
    "thumbnail": "https://picsum.photos/seed/thumb44/200/200",
    "title": "Content for YouTube Channel 2 - Post 3",
    "channel": "YouTube Channel 2",
    "platform": "youtube",
    "date": "2026-04-05T10:00:00Z",
    "reach": 19097,
    "engagement": 183370,
    "comments": 8279,
    "shares": 3685,
    "saves": 1352,
    "followersGained": 80,
    "performanceScore": 75,
    "status": "draft"
  },
  {
    "id": "cc_25",
    "thumbnail": "https://picsum.photos/seed/thumb45/200/200",
    "title": "Content for YouTube Channel 3 - Post 1",
    "channel": "YouTube Channel 3",
    "platform": "youtube",
    "date": "2026-04-18T10:00:00Z",
    "reach": 1172893,
    "engagement": 340154,
    "comments": 531,
    "shares": 4011,
    "saves": 279,
    "followersGained": 26,
    "performanceScore": 87,
    "status": "published"
  },
  {
    "id": "cc_26",
    "thumbnail": "https://picsum.photos/seed/thumb46/200/200",
    "title": "Content for YouTube Channel 3 - Post 2",
    "channel": "YouTube Channel 3",
    "platform": "youtube",
    "date": "2026-04-02T10:00:00Z",
    "reach": 1474361,
    "engagement": 325126,
    "comments": 5068,
    "shares": 2081,
    "saves": 1600,
    "followersGained": 394,
    "performanceScore": 98,
    "status": "draft"
  },
  {
    "id": "cc_27",
    "thumbnail": "https://picsum.photos/seed/thumb47/200/200",
    "title": "Content for YouTube Channel 4 - Post 1",
    "channel": "YouTube Channel 4",
    "platform": "youtube",
    "date": "2026-04-16T10:00:00Z",
    "reach": 1976499,
    "engagement": 200178,
    "comments": 5391,
    "shares": 966,
    "saves": 1823,
    "followersGained": 210,
    "performanceScore": 98,
    "status": "published"
  },
  {
    "id": "cc_28",
    "thumbnail": "https://picsum.photos/seed/thumb48/200/200",
    "title": "Content for YouTube Channel 5 - Post 1",
    "channel": "YouTube Channel 5",
    "platform": "youtube",
    "date": "2026-04-01T10:00:00Z",
    "reach": 1145298,
    "engagement": 363792,
    "comments": 4660,
    "shares": 2622,
    "saves": 1760,
    "followersGained": 291,
    "performanceScore": 97,
    "status": "published"
  },
  {
    "id": "cc_29",
    "thumbnail": "https://picsum.photos/seed/thumb49/200/200",
    "title": "Content for YouTube Channel 5 - Post 2",
    "channel": "YouTube Channel 5",
    "platform": "youtube",
    "date": "2026-04-16T10:00:00Z",
    "reach": 274187,
    "engagement": 497590,
    "comments": 8623,
    "shares": 2355,
    "saves": 1864,
    "followersGained": 440,
    "performanceScore": 98,
    "status": "published"
  },
  {
    "id": "cc_30",
    "thumbnail": "https://picsum.photos/seed/thumb50/200/200",
    "title": "Content for YouTube Channel 5 - Post 3",
    "channel": "YouTube Channel 5",
    "platform": "youtube",
    "date": "2026-04-16T10:00:00Z",
    "reach": 1853042,
    "engagement": 17058,
    "comments": 2637,
    "shares": 2042,
    "saves": 368,
    "followersGained": 487,
    "performanceScore": 80,
    "status": "published"
  },
  {
    "id": "cc_31",
    "thumbnail": "https://picsum.photos/seed/thumb51/200/200",
    "title": "Content for TikTok Channel 1 - Post 1",
    "channel": "TikTok Channel 1",
    "platform": "tiktok",
    "date": "2026-04-06T10:00:00Z",
    "reach": 1605973,
    "engagement": 349281,
    "comments": 2829,
    "shares": 2085,
    "saves": 1001,
    "followersGained": 212,
    "performanceScore": 73,
    "status": "published"
  },
  {
    "id": "cc_32",
    "thumbnail": "https://picsum.photos/seed/thumb52/200/200",
    "title": "Content for TikTok Channel 1 - Post 2",
    "channel": "TikTok Channel 1",
    "platform": "tiktok",
    "date": "2026-04-17T10:00:00Z",
    "reach": 1453818,
    "engagement": 470038,
    "comments": 645,
    "shares": 1306,
    "saves": 1184,
    "followersGained": 22,
    "performanceScore": 67,
    "status": "published"
  },
  {
    "id": "cc_33",
    "thumbnail": "https://picsum.photos/seed/thumb53/200/200",
    "title": "Content for TikTok Channel 1 - Post 3",
    "channel": "TikTok Channel 1",
    "platform": "tiktok",
    "date": "2026-04-13T10:00:00Z",
    "reach": 950512,
    "engagement": 242823,
    "comments": 9220,
    "shares": 2319,
    "saves": 559,
    "followersGained": 231,
    "performanceScore": 91,
    "status": "draft"
  },
  {
    "id": "cc_34",
    "thumbnail": "https://picsum.photos/seed/thumb54/200/200",
    "title": "Content for TikTok Channel 2 - Post 1",
    "channel": "TikTok Channel 2",
    "platform": "tiktok",
    "date": "2026-04-07T10:00:00Z",
    "reach": 1247133,
    "engagement": 322769,
    "comments": 3616,
    "shares": 560,
    "saves": 878,
    "followersGained": 415,
    "performanceScore": 79,
    "status": "published"
  },
  {
    "id": "cc_35",
    "thumbnail": "https://picsum.photos/seed/thumb55/200/200",
    "title": "Content for TikTok Channel 2 - Post 2",
    "channel": "TikTok Channel 2",
    "platform": "tiktok",
    "date": "2026-04-11T10:00:00Z",
    "reach": 194666,
    "engagement": 202190,
    "comments": 5360,
    "shares": 704,
    "saves": 897,
    "followersGained": 59,
    "performanceScore": 73,
    "status": "draft"
  },
  {
    "id": "cc_36",
    "thumbnail": "https://picsum.photos/seed/thumb56/200/200",
    "title": "Content for TikTok Channel 3 - Post 1",
    "channel": "TikTok Channel 3",
    "platform": "tiktok",
    "date": "2026-04-06T10:00:00Z",
    "reach": 475312,
    "engagement": 211917,
    "comments": 4898,
    "shares": 868,
    "saves": 1737,
    "followersGained": 166,
    "performanceScore": 78,
    "status": "draft"
  },
  {
    "id": "cc_37",
    "thumbnail": "https://picsum.photos/seed/thumb57/200/200",
    "title": "Content for TikTok Channel 3 - Post 2",
    "channel": "TikTok Channel 3",
    "platform": "tiktok",
    "date": "2026-04-20T10:00:00Z",
    "reach": 1780287,
    "engagement": 166350,
    "comments": 8188,
    "shares": 2695,
    "saves": 972,
    "followersGained": 140,
    "performanceScore": 80,
    "status": "published"
  },
  {
    "id": "cc_38",
    "thumbnail": "https://picsum.photos/seed/thumb58/200/200",
    "title": "Content for TikTok Channel 3 - Post 3",
    "channel": "TikTok Channel 3",
    "platform": "tiktok",
    "date": "2026-04-20T10:00:00Z",
    "reach": 323686,
    "engagement": 458365,
    "comments": 6707,
    "shares": 562,
    "saves": 306,
    "followersGained": 449,
    "performanceScore": 67,
    "status": "published"
  },
  {
    "id": "cc_39",
    "thumbnail": "https://picsum.photos/seed/thumb59/200/200",
    "title": "Content for TikTok Channel 4 - Post 1",
    "channel": "TikTok Channel 4",
    "platform": "tiktok",
    "date": "2026-04-19T10:00:00Z",
    "reach": 1138602,
    "engagement": 72493,
    "comments": 4104,
    "shares": 1955,
    "saves": 999,
    "followersGained": 78,
    "performanceScore": 98,
    "status": "published"
  },
  {
    "id": "cc_40",
    "thumbnail": "https://picsum.photos/seed/thumb60/200/200",
    "title": "Content for TikTok Channel 4 - Post 2",
    "channel": "TikTok Channel 4",
    "platform": "tiktok",
    "date": "2026-04-05T10:00:00Z",
    "reach": 601095,
    "engagement": 236631,
    "comments": 6516,
    "shares": 1402,
    "saves": 1553,
    "followersGained": 436,
    "performanceScore": 84,
    "status": "published"
  },
  {
    "id": "cc_41",
    "thumbnail": "https://picsum.photos/seed/thumb61/200/200",
    "title": "Content for TikTok Channel 4 - Post 3",
    "channel": "TikTok Channel 4",
    "platform": "tiktok",
    "date": "2026-04-07T10:00:00Z",
    "reach": 1325055,
    "engagement": 337781,
    "comments": 5727,
    "shares": 4312,
    "saves": 460,
    "followersGained": 88,
    "performanceScore": 66,
    "status": "published"
  },
  {
    "id": "cc_42",
    "thumbnail": "https://picsum.photos/seed/thumb62/200/200",
    "title": "Content for TikTok Channel 5 - Post 1",
    "channel": "TikTok Channel 5",
    "platform": "tiktok",
    "date": "2026-04-17T10:00:00Z",
    "reach": 1119037,
    "engagement": 346168,
    "comments": 3274,
    "shares": 472,
    "saves": 612,
    "followersGained": 106,
    "performanceScore": 69,
    "status": "published"
  }
];



export const COMMENT_SLA_DATA = [
  { platform: "facebook", name: "Facebook", percentage: 98, time: "1h 15m" },
  { platform: "youtube", name: "YouTube", percentage: 85, time: "4h 30m" },
  { platform: "tiktok", name: "TikTok", percentage: 72, time: "8h 10m" },
];

export const FILTER_OPTIONS = {
  platforms: [
    { id: 'all', name: 'Tất cả nền tảng' },
    { id: 'facebook', name: 'Facebook' },
    { id: 'youtube', name: 'YouTube' },
    { id: 'tiktok', name: 'TikTok' },
  ],
  groups: [
    { id: 'all', name: 'Tất cả nhóm', count: 12 },
    { id: 'brand', name: 'Thương hiệu cốt lõi', count: 3 },
    { id: 'support', name: 'CSKH & Hỗ trợ', count: 5 },
  ],
  savedViews: [
    { id: 'v1', name: 'Báo cáo điều hành hàng tuần', filters: { dateRange: '7d', platforms: ['facebook', 'youtube'], group: 'all' } },
  ]
};

// Heatmap data generator [dayOfWeek 0-6][hour 0-23]
export const generateHeatmapData = () => {
  const days = ['T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'CN'];
  return days.map(day => {
    return {
      name: day,
      data: Array.from({ length: 24 }).map((_, hour) => {
        // Create an organic pattern: more engagement around 11-13 and 19-22
        let intensity = Math.random() * 20;
        if ((hour >= 11 && hour <= 13) || (hour >= 19 && hour <= 22)) intensity += 50 + Math.random() * 30;
        if (hour >= 1 && hour <= 6) intensity = Math.random() * 5;
        return { hour, value: Math.floor(intensity) };
      })
    };
  });
};

